### ISSUE TITLE
Very Nice Work!

### ISSUE THREAD

**Issue by realaboo** [tflhyl/google-gson#1]
I found this very useful in my project where server responses cannot be altered. Thanks for the delighted work. Can this be done as an extension to Gson (by calling APIs provided by it I mean) instead of being part of it? In that case I can also benefit from Gson's new features or bug fixes by updating it to the latest version separately. Thanks very much :+1:

**Comment by tflhyl** [comment]
hi great to hear that. unfortunately i dont think that separating this as an extension is possible at the moment since i change a few things on the internals. i also dont think im going to spend much time  maintaining this anymore since im no longer using it for my day to day work. 

by the way i will try to update this to use the latest gson so that you can benefit from the latest features/bug fixes.

**Comment by realaboo** [comment]
Great, thanks again!

**Comment by tflhyl** [comment]
b0825836b278735ac9f7aa22c60accf9abf61d4a merged latest gson version and modified a bit. it passed the test so it should work. but since i'm not using this in any project right now, i can't give 100% guarantee. @realaboo
